spring:
  config:
    import: optional:file:.env[.properties] #.env파일 읽기
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: truvel-redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG # 이 부분을 추가하거나 DEBUG로 변경
#    org.springdoc: DEBUG             # SpringDoc OpenAPI 로그를 위한 추가 (선택 사항이지만 유용)
    alt_t.truvel: DEBUG


jwt:
  secret: ${JWT_SECRET}
